### ISSUE TITLE
Add docker compose

### ISSUE THREAD

**Issue by kortov** [kortov/teamcity-telegram-plugin#2]
There is a branch https://github.com/kortov/teamcity-telegram-plugin/tree/add-docker-compose

it's working, but agents have no names, so teamcity backup in files doesn't find agents. Improve it, add doc to readme and write about it to the repo maintainer. Maybe there is a better image without this backups, but I don't know about it

maybe it's possible to load config backup via cmd with some tool

**Comment by rusguliev** [comment]
Agent containers and server container not linked on network layer (agent container will try to connect to dns name "server":8111).
Add to docker-compose.yml link section for agent containers.
```
teamcity-agent:
    image: jetbrains/teamcity-agent
    links:
      - server
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=regular_agent
```
I tried to docker-compose up and discovered the successful operation of agents on the server.
